# Generated by Django 5.1.3 on 2024-11-18 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_cliente_documento_alter_cliente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(default='Particular', max_length=100),
        ),
    ]
