# Generated by Django 5.1.3 on 2024-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_cliente_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
