# Generated by Django 5.1.3 on 2024-11-18 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_cliente_documento_alter_cliente_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.SmallIntegerField(max_length=15, unique=True),
        ),
    ]
