# Generated by Django 5.1.3 on 2024-11-18 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.SmallIntegerField(max_length=15, unique=True),
        ),
    ]
