# Generated by Django 5.1.3 on 2024-11-18 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='prioridad',
            field=models.CharField(default='Media', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actividad',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
