# Generated by Django 5.1.3 on 2024-11-18 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_actividad_hora_alter_cliente_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='hora',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
