# Generated by Django 5.1.2 on 2024-11-25 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_actividad_hora_alter_actividad_modified_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='observaciones',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='actividad_realizada',
            field=models.CharField(default='Ninguna', max_length=140),
        ),
    ]
