# Generated by Django 5.1.2 on 2024-11-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_actividad_observaciones_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='empresa',
            field=models.CharField(default='Particular', max_length=100),
        ),
    ]
