# Generated by Django 5.1.2 on 2024-11-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_cliente_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actividad',
            old_name='actividad_realizada',
            new_name='actividad_anterior',
        ),
        migrations.RenameField(
            model_name='actividad',
            old_name='actividad_proxima',
            new_name='actividad_programada',
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultima_actividad',
            field=models.CharField(default='No disponible', max_length=140),
        ),
    ]
