# Generated by Django 5.1.2 on 2024-11-25 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_rename_actividad_realizada_actividad_actividad_anterior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='prioridad',
            field=models.CharField(default='Media', max_length=25),
        ),
    ]
