# Generated by Django 5.1.2 on 2024-12-02 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_actividad_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.CharField(max_length=250)),
                ('modalidad', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('Iniciado', 'Iniciado'), ('Terminado', 'Terminado'), ('Suspendido', 'Suspendido')], default='Iniciado', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='main.cliente')),
            ],
        ),
    ]
