# Generated by Django 5.1.2 on 2024-12-06 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_cliente_telefono_casa_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CP',
            new_name='cp',
        ),
    ]
