# Generated by Django 5.1.3 on 2024-12-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_cliente_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultima_actividad',
            field=models.DateField(blank=True, max_length=140, null=True),
        ),
    ]
