# Generated by Django 5.1.3 on 2024-12-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_cliente_ultima_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='ultima_actividad',
            field=models.CharField(default='No disponible', max_length=140),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultima_compra',
            field=models.CharField(default='No disponible', max_length=140),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='ultimo_pago',
            field=models.CharField(default='No disponible', max_length=140),
        ),
    ]
