# Generated by Django 5.1.3 on 2024-12-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_cliente_ultima_actividad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='numero_cliente',
            field=models.SmallIntegerField(),
        ),
    ]
