# Generated by Django 5.1.2 on 2024-12-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_cliente_ciudad_alter_cliente_cp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='observaciones',
            field=models.CharField(default='No disponible', max_length=140),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='actividad_anterior',
            field=models.CharField(default='No disponible', max_length=140),
        ),
    ]
