# Generated by Django 5.1.2 on 2024-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_actividad_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='proxima_actividad',
            field=models.CharField(default='No disponible', max_length=140),
        ),
    ]
